COMMAND_COUNT_ALIASES = ["command-count", "commandcount"]
WEAPON_INFO_ALIASES = ["wi", "weaponinfo", "wepinfo", "wep-info"]
WEAPON_TIPS_ALIASES = ["wt", "weapontips", "weptips", "wep-tips", "tipsandtrivia", "tips-and-trivia"]
XP_ALIASES = ["xp-chart", "xpchart"]
GUESS_THE_WEAPON_ALIASES = ["guesstheweapon", "gtw", "guessthewep", "guess-the-wep"]